export const defaultTheme = {
  'base-title': '#E7EDF4',
  'base-subtitle': '#C4D4E3',
  'base-text': '#AFC2D4',
  'base-span': '#7B96B2',
  'base-label': '#3A536B',
  'base-border': '#1C2F41',
  'base-post': '#112131',
  'base-profile': '#0B1B2B',
  'base-background': '#071422',
  'base-input': '#040F1A',
  'brand-blue': '#3294F8',

  'font-title-l': '2.4rem/1.3 "Nunito",sans-serif',
  'font-title-m': '2.0rem "Nunito",sans-serif',
  'font-title-s': '1.8rem "Nunito",sans-serif',
  'font-text-m': '1.6rem "Nunito",sans-serif',
  'font-text-s': '1.4rem "Nunito",sans-serif',
  'font-component-link': '1.2rem "Nunito",sans-serif',
} as const;
